// TYPE USER
export const SIGNIN_API = "SIGNIN_API";

export const USLOGIN = "USLOGIN";

export const GET_SEARCH_USER_SAGA = "GET_SEARCH_USER_SAGA";
export const GET_SEARCH_USER = "GET_SEARCH_USER";

export const SIGN_UP_SAGA = "SIGN_UP_SAGA"

export const GET_ALL_USER_SAGA = "GET_ALL_USER_SAGA";
export const GET_ALL_USER = "GET_ALL_USER"

export const DELETE_USER_SAGA = "DELETE_USER_SAGA";

export const EDIT_USER_SAGA = "EDIT_USER_SAGA";

export const SEARCH_USER_SAGA = "SEARCH_USER_SAGA"
export const SEARCH_USER = "SEARCH_USER"

// TYPE PROJECT
export const ADD_MEMBER_SAGA = "ADD_MEMBER_SAGA";

export const REMOVE_MEMBER_SAGA = "REMOVE_MEMBER_SAGA";

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";

export const EDIT_PROJECT_CYBERBUGS_SAGA = "EDIT_PROJECT_CYBERBUGS_SAGA";
export const GET_PROJECT_EDIT = "GET_PROJECT_EDIT"

export const DELETE_PROJECT_SAGA = "DELETE_PROJECT_SAGA";

export const GET_ALL_PROJECT_CATEGORY_SAGA = "GET_ALL_PROJECT_CATEGORY_SAGA";
export const GET_ALL_PROJECT_CATEGORY = "GET_ALL_PROJECT_CATEGORY"

export const CREATE_PROJECT_SAGA = "CREATE_PROJECT_SAGA";

export const GET_ALL_PROJECT_MANAGEMENT_SAGA = "GET_ALL_PROJECT_MANAGEMENT_SAGA";
export const GET_ALL_PROJECT_MANAGEMENT = "GET_ALL_PROJECT_MANAGEMENT"

export const GET_PROJECT_DETAIL_SAGA = "GET_PROJECT_DETAIL_SAGA";
export const GET_PROJECT_DETAIL = "GET_PROJECT_DETAIL";

// MODAL CREATE TASK
export const GET_ALL_PROJECT_FORM_CREATE_TASK_SAGA = "GET_ALL_PROJECT_FORM_CREATE_TASK_SAGA";
export const GET_ALL_PROJECT_FORM_CREATE_TASK = "GET_ALL_PROJECT_FORM_CREATE_TASK";

export const GET_TASK_TYPE_FORM_CREATE_TASK_SAGA = "GET_TASK_TYPE_FORM_CREATE_TASK_SAGA";
export const GET_TASK_TYPE_FORM_CREATE_TASK = "GET_TASK_TYPE_FORM_CREATE_TASK";

export const GET_PRIORITY_FORM_CREATE_TASK_SAGA = "GET_PRIORITY_FORM_CREATE_TASK_SAGA";
export const GET_PRIORITY_FORM_CREATE_TASK = "GET_PRIORITY_FORM_CREATE_TASK";

export const GET_STATUS_FORM_CREATE_TASK_SAGA = "GET_STATUS_FORM_CREATE_TASK_SAGA";
export const GET_STATUS_FORM_CREATE_TASK = "GET_STATUS_FORM_CREATE_TASK";

export const CREATE_TASK_FORM_CREATE_TASK_SAGA = "CREATE_TASK_FORM_CREATE_TASK_SAGA";

export const GET_USER_BY_PROJECT_FORM_CREATE_TASK_SAGA = "GET_USER_BY_PROJECT_FORM_CREATE_TASK_SAGA";
export const GET_USER_BY_PROJECT_FORM_CREATE_TASK = "GET_USER_BY_PROJECT_FORM_CREATE_TASK";

// TYPE TASK
export const GET_TASK_DETAIL_MODAL_CYBERBUGS_SAGA = "GET_TASK_DETAIL_MODAL_CYBERBUGS_SAGA";
export const GET_TASK_DETAIL_MODAL_CYBERBUGS = "GET_TASK_DETAIL_MODAL_CYBERBUGS";

export const UPDATE_STATUS_MODAL_CYBERBUGS_SAGA = "UPDATE_STATUS_MODAL_CYBERBUGS_SAGA";

export const CHANGE_VALUE_MODAL_CYBERBUGS = "CHANGE_VALUE_MODAL_CYBERBUGS"
export const CHANGE_VALUE_MEMBERS_MODAL_CYBERBUGS = "CHANGE_VALUE_MEMBERS_MODAL_CYBERBUGS"
export const DELETE_MEMBERS_MODAL_CYBERBUGS = "DELETE_MEMBERS_MODAL_CYBERBUGS"

export const UPDATE_TASK_MODAL_CYBERBUGS = "UPDATE_TASK_MODAL_CYBERBUGS"

export const HANDLE_CHANGE_CALL_API_MODAL_CYBERBUGS = "HANDLE_CHANGE_CALL_API_MODAL_CYBERBUGS";

// TYPE DRAWER
export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";

//MODAL DRAWER FORM
export const OPEN_FORM_CREATE_TASK = "OPEN_FORM_CREATE_TASK";
export const SUBMIT_FORM_CREATE_TASK = "SUBMIT_FORM_CREATE_TASK";

export const OPEN_DRAWER_EDIT_PROJECT = "OPEN_DRAWER_EDIT_PROJECT";
export const SUBMIT_FORM_EDIT_PROJECT = "SUBMIT_FORM_EDIT_PROJECT";

export const OPEN_FORM_EDIT_USER = "OPEN_FORM_EDIT_USER";
export const SUBMIT_FORM_EDIT_USER = "SUBMIT_FORM_EDIT_USER";

// COMMENT
export const ADD_COMMENT_SAGA = "ADD_COMMENT_SAGA"
export const EDIT_COMMENT_SAGA = "EDIT_COMMENT_SAGA"
export const DELETE_COMMENT_SAGA = "DELETE_COMMENT_SAGA"